### ISSUE TITLE
functional issues

### ISSUE THREAD

**Issue by lenadg18** [algosup/2024-2025-project-2-serious-game-team-1#2]
error line 89:  **a** lovely match between serious [...] and **a** video game's mechanics [...] engaging, and federating way.

error line 96: [...]awareness**,** and develop critical thinking and problem-solving skills

error line 97:**S**ources

error line 114 at 116: but **the** village mayor ordered

error line 120 at 126: [...] **basic** features that we must have for the prototype:
- **the** ability to control **the** character's movement (move forward, backward, left, right**,** and jump)
- two **different** biomes (village and beach)
- three quests per **biome**

error line 130: The village has some houses and **buildings** where you can find the town hall, the library, a shop**,** and the museum.

error line 139: The beach is a part of the map where you can walk and swim to clean up, and protect the ocean life.
correction: The beach is a part of the map where you can walk and swim to clean **up and** protect the ocean life.

error line 152:  add quests (until 10 per **biome**)

error line 162: convince villagers to leave **and** use **a** bike

error line 166: The forest is a place where you can find animals and some **locations** where **humans** leave **their footprints**.

 error line 176: There is a farm in the fields where you can help the farmer to cultivate, and take care **of** important natural **resources**.

error line 223: 
When the player **opens** the game, **the first open window** is the Home page below.
Firstly, the player can **modify** some settings to adapt the game as he **wants**.

error line 233: When the player **launches** his game, he has the following interface :
error line 237: **mini-map**, top view (top right)

error line 244:
When the player **presses the** "e" keyboard, the inventory **opens**. You can **recover** all **objects** you have on the left side and you can have the description and all details about the object on the right side when you pass the mousse on it.

error line 250 at 253:
When the player **launches** his part, He can **press** the "esc" keyboard and the menu window **opens**.
Firstly, the player can **modify** some settings to adapt the game as he **wants**.
The second button is to save his part. Thanks **to that**, the player quit the game and **came** back later thanks **to the** load button on the home page.

error line 259 at 267: During the game, you can collect multiple **successes** like
- You **entirely** clean the village
- You **entirely** clean the beach
You can also collect data about climate change, Fossil fuels**,** and renewable energies.

error line 273: always moving and curious. She loves wearing **colourful** t-shirts with animal or nature-themed prints 
error line 297:  E. Non-functional **Requirements**

error line 303: We design some **objects** of the game, but **for** time reasons, we use assets listed below:
error line 314: **furniture**
error line 318: b. Time **development**
error line 320 at 321:
We have 61 hours and 45 minutes dedicated to **developing** the game.
This amount of time **doesn't** take **into** consideration any overtime that members can do during the project.

error line 358 at 360:
You embody a forester, and you have one mission, save **the French** forest by **making decisions** and **managing** flora and fauna[^4].
This game is **developed** for the French Government and the ONF[^5] and has the Néo Terra label[^6].
The aim of this game is to experiment with different forest management methods adapted to tomorrow's climate and **develop** innovative awareness-raising tools to explain forest management to the general public.

error line 366 at 367:
Zeus is your name, you can control a city and help it to reduce **pollution**, and become **a utopic** city where it's a good place to live.
This game is **developed** by Hakatah[^7] whose aim is to help people understand the phenomenon of climate change and **raise** awareness of its consequences.

error line 373 at 374:
The player **takes** on the role of mayor of his fictional city and **attempts** to build an urban environment that is energy efficient while still meeting the needs of its citizens. He **earns** money and **decides** how to spend it, 

error line 380:
 in the **worst-case** scenario, lead to an adaptation of **behaviour** that would go against the climate and the very idea of the game.
error line 382:
The third problem is **the** risk of transmitting too much information through the game and therefore losing the educational and fun value of the game.

error line 386:
Our game doesn't need to save **players' data**, but if the game evolves and **we** need to save information, we need **to be interested in the regimentation of data backups*.

**Comment by Gregory-Pagnoux** [comment]
With the following error :
error line 273: She loves wearing colourful t-shirts 
it depends on the language that I choose. If it's British or American.

**Comment by Gregory-Pagnoux** [comment]
for the following error
error line 366 at 367:
Zeus is your name, you can control a city and help it to reduce pollution, and become a utopic city 
the pollution was already written like that, ans are you for the seconde error ? Because normally we put an "n" when the word after start by a vowel. If you assure to me that it's an error, I correct it.

**Comment by Gregory-Pagnoux** [comment]
for the following error
error line 380:
lead to an adaptation of behaviour that would go
behavior was already written like that.

**Comment by Gregory-Pagnoux** [comment]
Correction done and pushed, ready for a second review. ;)

**Comment by lenadg18** [comment]
@Gregory-Pagnoux 
error line 92:
The term **of** "serious game" is used since the beginning of the twentieth century, and the best-known game is The Landlord's Game (predecessor of Monopoly) in 1903.
correction : 
The term "serious game" **has been** used since the beginning of the twentieth century, and the best-known game is The Landlord's Game (predecessor of Monopoly) in 1903.

error line 115: is a serious game where the player incarn a character named Bob. 
correction: is a serious game in **which players take on the role of a character called Bob.**

error line 115: but the village mayor ordered him to renovate the house with renewable **energy**.
error line 116: You'll have to carry out missions all over the map to convert all fossil fuels **to** renewable energies and improve your house. 

error line 123: (move forward, backward, left, right**,** and jump)
error line 134: learn some **techniques** and new things on ecology

error line 149: Here are all **the** optional features that we can find in the game after the prototype phase:
error line 225: Firstly, the player can modify some settings to adapt the game as he **wants**.
error line 252: he can **press** the "esc" keyboard and the menu window opens.

error line 355: there are two other games that partially cover 
correction:** two other games partially cover**

error line 368: Zeus is your name, you can control a city and help it to reduce **(not the)**pollution,
error line 369: This game **was** developed by Hakatah[^7]

error liner 388: we need **to be interested in the reglementation** of data backups.**

error line 423: The quality of being whole and complete. It's the fact that information is certified as true and we can believe it.
error line 431: Abbreviation for Office National des Forêts. The **organization** was created in 1966 and has 5 fundamental missions: to develop wood resources, to act for the environment, to welcome the public to the forest, to prevent natural risks**,** and to offer tailor-made services.

error line 435:Their objective: **is to** accelerate change and support the process.

error line 439: They run educational workshops and **organize** Game Jams (the event at which Nuage was born).

**Comment by Gregory-Pagnoux** [comment]
done
