### ISSUE TITLE
user manual,correction

### ISSUE THREAD

**Issue by lenadg18** [algosup/2024-2025-project-2-serious-game-team-1#20]
page 8,Main Menu : Quit **Exit** the game and **return** to your desktop. 

page 11,Hardware Compatibility Problems :  If you **encounter** compatibility problems, 

page 12,Color & Brightness : Color & Brightness Color and brightness adjustments **have** not yet **been** implemented.

**Comment by GuillaumeDespaux** [comment]
- [X] Page 8
- [ ] Page 11 (Can you be more specific? I do not see the error mentioned for this one.
- [X] Page 12

You can see the last version of it here :
https://github.com/algosup/2024-2025-project-2-serious-game-team-1/commit/2322b51d23b6a17876392e63cbdea4dfc61bd972

**Comment by lenadg18** [comment]
sorry, there are no mistakes, I just misread the word
